import Foundation

/// Turns a `HealthReport` into a single, agent-friendly Markdown document.
///
/// Design goals:
///  - Front-matter style header so an LLM immediately knows scope + freshness.
///  - One section per data domain, only emitted when data exists.
///  - Tables for scannable density; explicit units everywhere.
///  - A short "How to read this" note so an agent doesn't misinterpret aggregates.
enum MarkdownGenerator {

    static func generate(from report: HealthReport) -> String {
        var md = ""

        md += header(report)
        md += summaryBlock(report)

        // Aggregated summary sections (Quick & Full only — Raw skips them).
        if report.mode.includesSummary {
            for section in report.sectionsWithData {
                switch section {
                case .profile:
                    md += profileSection(report.profile)
                case .sleep:
                    md += sleepSection(report.sleep)
                case .mindfulness:
                    md += mindfulSection(report.mindful)
                case .workouts:
                    md += workoutsSection(report.workouts)
                default:
                    md += quantitySection(section, report: report)
                }
            }
        }

        // Raw per-sample dump (Full & Raw).
        if report.mode.includesRaw && (!report.rawSeries.isEmpty || !report.rawCategorySeries.isEmpty) {
            md += rawDumpSection(report)
        }

        md += footer()
        return md
    }

    // MARK: - Header

    private static func header(_ report: HealthReport) -> String {
        var s = "# Apple Health Export\n\n"
        s += "> Generated by **HealthMarkdown** for use with an AI assistant.\n\n"
        s += "| | |\n|---|---|\n"
        s += "| **Generated** | \(Fmt.dateTime(report.generatedAt)) |\n"
        s += "| **Window** | \(report.range.title) (\(Fmt.shortDate(report.interval.start)) → \(Fmt.shortDate(report.interval.end))) |\n"
        switch report.mode {
        case .full:
            s += "| **Export** | Full — aggregated summary **plus every raw sample** |\n"
            s += "| **Raw samples** | \(report.rawSampleCount) |\n"
        case .raw:
            s += "| **Export** | Raw — every raw sample, no aggregation |\n"
            s += "| **Raw samples** | \(report.rawSampleCount) |\n"
        case .quick:
            s += "| **Export** | Quick — aggregated summary |\n"
        }
        s += "| **Sections** | \(report.sectionsWithData.map(\.title).joined(separator: ", ")) |\n\n"
        return s
    }

    private static func summaryBlock(_ report: HealthReport) -> String {
        var s = "## How to read this\n\n"
        switch report.mode {
        case .full:
            s += "This is a **full export**. It has two parts:\n\n"
            s += "1. **Summary** (below) — aggregated totals/averages per metric, for a quick overview.\n"
            s += "2. **Raw Samples** (at the end) — every individual measurement exactly as recorded in Apple Health, "
            s += "with its precise timestamp, value, and source. Nothing is bucketed or averaged there.\n\n"
            s += "- Cumulative metrics report a **total** and **daily average**; point-in-time metrics report **average / min / max** and the **latest** reading.\n"
            s += "- Empty or unmeasured metrics are omitted entirely.\n\n"
        case .raw:
            s += "This is a **raw export** — no aggregation at all. Every section below is the "
            s += "**Raw Samples** dump: one table per metric, one row per individual measurement, "
            s += "with its exact timestamp, value, and source, straight from Apple Health.\n\n"
        case .quick:
            s += "This is a **quick export** — aggregated values only:\n\n"
            s += "- Cumulative metrics (steps, energy, distance, nutrition) report the **total** and a **daily average** over the window.\n"
            s += "- Point-in-time metrics (heart rate, weight, blood oxygen) report **average / min / max** and the **latest** reading.\n"
            s += "- Empty or unmeasured metrics are omitted entirely.\n\n"
        }
        s += "---\n\n"
        return s
    }

    // MARK: - Quantity sections

    private static func quantitySection(_ section: HealthSection, report: HealthReport) -> String {
        let metrics = report.quantities.filter { $0.spec.section == section && $0.hasData }
        guard !metrics.isEmpty else { return "" }

        var s = "## \(section.title)\n\n"

        let cumulative = metrics.filter { $0.spec.aggregation == .cumulativeSum }
        let discrete = metrics.filter { $0.spec.aggregation == .discreteAverage }

        if !cumulative.isEmpty {
            s += "| Metric | Total | Daily avg |\n|---|---|---|\n"
            for m in cumulative {
                let total = Fmt.value(m.total, m.spec) ?? "—"
                let daily = Fmt.value(m.dailyAverage, m.spec) ?? "—"
                s += "| \(m.spec.title) | \(total) | \(daily) |\n"
            }
            s += "\n"
        }

        if !discrete.isEmpty {
            s += "| Metric | Average | Min | Max | Latest |\n|---|---|---|---|---|\n"
            for m in discrete {
                let avg = Fmt.value(m.average, m.spec) ?? "—"
                let mn = Fmt.value(m.min, m.spec) ?? "—"
                let mx = Fmt.value(m.max, m.spec) ?? "—"
                var latest = "—"
                if let r = m.mostRecent {
                    let val = Fmt.value(r, m.spec) ?? "—"
                    if let d = m.mostRecentDate {
                        latest = "\(val) _(\(Fmt.shortDate(d)))_"
                    } else {
                        latest = val
                    }
                }
                s += "| \(m.spec.title) | \(avg) | \(mn) | \(mx) | \(latest) |\n"
            }
            s += "\n"
        }

        return s
    }

    // MARK: - Profile

    private static func profileSection(_ p: ProfileSummary) -> String {
        guard p.hasData else { return "" }
        var s = "## Profile\n\n"
        if let age = p.ageYears { s += "- **Age:** \(age)\n" }
        if let sex = p.biologicalSex { s += "- **Biological sex:** \(sex)\n" }
        if let blood = p.bloodType { s += "- **Blood type:** \(blood)\n" }
        if let skin = p.skinType { s += "- **Fitzpatrick skin type:** \(skin)\n" }
        s += "\n"
        return s
    }

    // MARK: - Sleep

    private static func sleepSection(_ sleep: SleepSummary) -> String {
        guard sleep.hasData else { return "" }
        var s = "## Sleep\n\n"
        s += "- **Nights recorded:** \(sleep.nights)\n"
        if sleep.nights > 0 {
            s += "- **Average asleep / night:** \(Fmt.duration(sleep.averageAsleepPerNight))\n"
        }
        s += "- **Total asleep:** \(Fmt.duration(sleep.totalAsleep))\n"
        if sleep.inBed > 0 { s += "- **Total in bed:** \(Fmt.duration(sleep.inBed))\n" }

        let hasStages = sleep.rem > 0 || sleep.core > 0 || sleep.deep > 0
        if hasStages {
            s += "\n| Stage | Total |\n|---|---|\n"
            if sleep.rem > 0 { s += "| REM | \(Fmt.duration(sleep.rem)) |\n" }
            if sleep.core > 0 { s += "| Core | \(Fmt.duration(sleep.core)) |\n" }
            if sleep.deep > 0 { s += "| Deep | \(Fmt.duration(sleep.deep)) |\n" }
            if sleep.awake > 0 { s += "| Awake | \(Fmt.duration(sleep.awake)) |\n" }
        }
        s += "\n"
        return s
    }

    // MARK: - Mindfulness

    private static func mindfulSection(_ m: MindfulSummary) -> String {
        guard m.hasData else { return "" }
        var s = "## Mindfulness\n\n"
        s += "- **Sessions:** \(m.sessionCount)\n"
        s += "- **Total time:** \(Fmt.duration(m.totalDuration))\n\n"
        return s
    }

    // MARK: - Workouts

    private static func workoutsSection(_ w: WorkoutsSummary) -> String {
        guard w.hasData else { return "" }
        var s = "## Workouts\n\n"
        s += "- **Sessions:** \(w.workouts.count)\n"
        s += "- **Total time:** \(Fmt.duration(w.totalDuration))\n"
        if w.totalEnergy > 0 { s += "- **Total active energy:** \(Fmt.number(w.totalEnergy, precision: 0)) kcal\n" }
        if w.totalDistance > 0 { s += "- **Total distance:** \(Fmt.number(w.totalDistance, precision: 1)) km\n" }
        s += "\n"

        let recent = Array(w.workouts.prefix(20))
        s += "| Date | Activity | Duration | Energy | Distance |\n|---|---|---|---|---|\n"
        for workout in recent {
            let energy = workout.energyKcal.map { "\(Fmt.number($0, precision: 0)) kcal" } ?? "—"
            let distance = workout.distanceKm.map { "\(Fmt.number($0, precision: 2)) km" } ?? "—"
            s += "| \(Fmt.shortDate(workout.start)) | \(workout.activityName) | \(Fmt.duration(workout.duration)) | \(energy) | \(distance) |\n"
        }
        if w.workouts.count > recent.count {
            s += "\n_+\(w.workouts.count - recent.count) more workouts not listed._\n"
        }
        s += "\n"
        return s
    }

    // MARK: - Daily breakdown (full export)

    private static func rawDumpSection(_ report: HealthReport) -> String {
        let metricCount = report.rawSeries.count + report.rawCategorySeries.count
        var s = "## Raw Samples\n\n"
        s += "_Every individual measurement as recorded in Apple Health — no bucketing, no averaging. "
        s += "One table per metric; each row is a single sample with its exact start/end time, value, and source. "
        s += "This is where the real time series live: weight, heart rate, HRV and sleep all appear here as full curves._\n\n"
        s += "**\(report.rawSampleCount) raw samples across \(metricCount) metrics.**\n\n"

        // Group both quantity and category series by section, canonical order.
        let quantBySection = Dictionary(grouping: report.rawSeries, by: { $0.spec.section })
        let catBySection = Dictionary(grouping: report.rawCategorySeries, by: { $0.section })

        for section in HealthSection.allCases {
            let quants = quantBySection[section]?.sorted { $0.spec.title < $1.spec.title } ?? []
            let cats = catBySection[section]?.sorted { $0.title < $1.title } ?? []
            guard !quants.isEmpty || !cats.isEmpty else { continue }
            s += "### \(section.title)\n\n"

            // ISO-8601 timestamps: compact, unambiguous for an agent, and the
            // formatter is cached so this stays fast even at 100k+ rows.
            for serie in quants {
                s += "#### \(serie.spec.title) (\(serie.spec.unitLabel)) — \(serie.samples.count) samples\n\n"
                s += "| Start | End | Value | Source |\n|---|---|---|---|\n"
                for sample in serie.samples {
                    let value = Fmt.number(sample.value, precision: serie.spec.precision)
                    let end = sample.end == sample.start ? "—" : Fmt.isoTimestamp(sample.end)
                    let source = sample.source ?? "—"
                    s += "| \(Fmt.isoTimestamp(sample.start)) | \(end) | \(value) | \(source) |\n"
                }
                s += "\n"
            }

            for serie in cats {
                s += "#### \(serie.title) — \(serie.samples.count) \(serie.unitLabel)s\n\n"
                s += "| Start | End | \(serie.unitLabel.capitalized) | Source |\n|---|---|---|---|\n"
                for sample in serie.samples {
                    let source = sample.source ?? "—"
                    s += "| \(Fmt.isoTimestamp(sample.start)) | \(Fmt.isoTimestamp(sample.end)) | \(sample.label) | \(source) |\n"
                }
                s += "\n"
            }
        }
        return s
    }

    private static func footer() -> String {
        var s = "---\n\n"
        s += "_All data was read on-device via Apple HealthKit and never transmitted by HealthMarkdown. "
        s += "Share this file with an AI assistant for analysis at your discretion._\n"
        return s
    }
}
